apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-app
  template:
    metadata:
      labels:
        app: odoo-app
    spec:
      containers:
        - name: odoo
          image: odoo-custom:latest
          ports:
            - containerPort: 8069
          env:
            - name: HOST
              value: odoo-db
            - name: USER
              value: odoo
            - name: PASSWORD
              value: odoo
          volumeMounts:
            - name: odoo-code
              mountPath: /usr/src/odoo
            - name: odoo-addons
              mountPath: /mnt/extra-addons
            - name: odoo-config
              mountPath: /etc/odoo
      volumes:
        - name: odoo-code
          hostPath:
            path: /home/tu_usuario/odoo-community
        - name: odoo-addons
          hostPath:
            path: /home/tu_usuario/addons
        - name: odoo-config
          hostPath:
            path: /home/tu_usuario/odoo.conf
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-service
spec:
  type: NodePort
  selector:
    app: odoo-app
  ports:
    - port: 8069
      targetPort: 8069
      nodePort: 30069
