apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-db
  template:
    metadata:
      labels:
        app: odoo-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: odoo
            - name: POSTGRES_PASSWORD
              value: odoo
            - name: POSTGRES_DB
              value: postgres
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: odoo-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-db
spec:
  selector:
    app: odoo-db
  ports:
    - port: 5432
      targetPort: 5432
